# ServiceAccount Patch - IRSA 적용
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-sa
  annotations:
    # Terraform에서 생성한 IAM Role ARN 주입 (값은 배포 시 치환되거나 하드코딩)
    eks.amazonaws.com/role-arn: IRSA_ROLE_ARN_PLACEHOLDER
