# Dev 환경용 HPA (테스트 및 비용 절약 목적)
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: app
  minReplicas: 1
  maxReplicas: 3 # Dev는 최대 3개로 제한
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 80 # Dev는 여유롭게
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60 # 빠른 축소 (비용 절약)
